--- #YAML:1.0
name:               SQL-Yapp
version:            2
abstract:           SQL syntax in Perl with compile-time syntax checks
author:
    - Henrik Theiling <cpan@theiling.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Data::Dumper:    0
    Filter::Simple:  0
    Hash::Util:      0
    Scalar::Util:    0
    Test::More:      0
    Text::Balanced:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
